import React, { useEffect, useMemo, useState } from "react";
import sdk from "../../../sdk";

export default function SkillsSection({ saving, toast, act }) {
  const [skills, setSkills] = useState([]);
  const [newSkillPath, setNewSkillPath] = useState("");
  const [autoSkills, setAutoSkills] = useState([]);
  const [expandedDomain, setExpandedDomain] = useState(null);
  const [viewMode, setViewMode] = useState("list"); // "list" | "domains"

  const refreshSkills = () => sdk.skills.list().then(r => setSkills(r.skills || [])).catch(() => {});

  useEffect(() => {
    refreshSkills();
    sdk.skills.autoGenerated().then(r => setAutoSkills(r.skills || [])).catch(() => {});
  }, []);

  // Group auto-generated skills by domain
  const domainGroups = useMemo(() => {
    const groups = {};
    autoSkills.forEach(s => {
      const domain = s.domain || "uncategorized";
      if (!groups[domain]) groups[domain] = [];
      groups[domain].push(s);
    });
    return Object.entries(groups).sort(([a], [b]) => a.localeCompare(b));
  }, [autoSkills]);

  return (
    <div className="settings-section">
      <h3>Installed Skills</h3>
      {skills.length === 0 && <div className="empty-state"><span className="empty-state-text">No skills installed</span></div>}
      <div className="integration-list">
        {skills.map(s => (
          <div key={s.id} className="integration-card">
            <header>
              <div><strong>{s.name}</strong> <span className="badge badge-info">v{s.version}</span><br/><small>{s.description}</small></div>
              <button className="btn-danger" style={{height:24,fontSize:11}} disabled={saving} onClick={() => act(async () => { await sdk.skills.uninstall(s.id); await refreshSkills() }, `Skill "${s.name}" uninstalled`)}>Uninstall</button>
            </header>
          </div>
        ))}
      </div>

      {autoSkills.length > 0 && <>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12}}>
          <h3 style={{margin:0}}>Auto-Generated Skills <span className="badge badge-warning" style={{fontSize:9,marginLeft:4}}>{autoSkills.length}</span></h3>
          <div style={{display:"flex",gap:2}}>
            <button style={{fontSize:10,height:22,padding:"0 8px",background:viewMode==="list"?"var(--accent-dim)":"transparent",border:viewMode==="list"?"1px solid var(--accent)":"1px solid var(--border)",color:viewMode==="list"?"var(--accent)":"var(--text-muted)",borderRadius:4,cursor:"pointer"}} onClick={()=>setViewMode("list")}>List</button>
            <button style={{fontSize:10,height:22,padding:"0 8px",background:viewMode==="domains"?"var(--accent-dim)":"transparent",border:viewMode==="domains"?"1px solid var(--accent)":"1px solid var(--border)",color:viewMode==="domains"?"var(--accent)":"var(--text-muted)",borderRadius:4,cursor:"pointer"}} onClick={()=>setViewMode("domains")}>Domains</button>
          </div>
        </div>

        {/* Domain KPI bar */}
        <div className="kpi-grid" style={{gridTemplateColumns:`repeat(${Math.min(domainGroups.length, 5)}, 1fr)`,marginTop:6}}>
          {domainGroups.slice(0, 5).map(([domain, items]) => (
            <div key={domain} className="kpi-card" style={{cursor:"pointer"}} onClick={()=>{setViewMode("domains");setExpandedDomain(expandedDomain===domain?null:domain)}}>
              <div className="kpi-label">{domain}</div>
              <div className="kpi-value">{items.length}</div>
            </div>
          ))}
        </div>

        {viewMode === "list" && autoSkills.map((s, i) => (
          <div key={i} className="card" style={{padding:"8px 12px",marginBottom:4}}>
            <div style={{display:"flex",alignItems:"center",gap:6}}>
              <span className="badge badge-warning" style={{fontSize:9}}>auto</span>
              <strong style={{fontSize:12}}>{s.tool_id || s.name || "skill"}</strong>
              {s.domain && <span className="badge badge-neutral">{s.domain}</span>}
            </div>
            {s.description && <div style={{fontSize:10,color:"var(--text-muted)",marginTop:2}}>{s.description}</div>}
          </div>
        ))}

        {viewMode === "domains" && domainGroups.map(([domain, items]) => (
          <div key={domain} className="card" style={{padding:0,overflow:"hidden",marginBottom:4}}>
            <div className="item-row" style={{padding:"8px 12px",cursor:"pointer"}} onClick={()=>setExpandedDomain(expandedDomain===domain?null:domain)}>
              <span style={{fontSize:10,color:"var(--text-muted)",marginRight:4}}>{expandedDomain===domain?"\u25BC":"\u25B6"}</span>
              <span style={{fontSize:12,fontWeight:600,flex:1}}>{domain}</span>
              <span className="badge badge-neutral">{items.length} skills</span>
            </div>
            {expandedDomain === domain && <div style={{borderTop:"1px solid var(--border)",padding:"4px 12px 8px"}}>
              {items.map((s, i) => (
                <div key={i} style={{padding:"4px 0",borderBottom:i < items.length-1 ? "1px solid rgba(255,255,255,0.03)" : "none"}}>
                  <div style={{display:"flex",alignItems:"center",gap:6}}>
                    <span className="badge badge-warning" style={{fontSize:8}}>auto</span>
                    <span style={{fontSize:11,fontWeight:500}}>{s.tool_id || s.name}</span>
                  </div>
                  {s.description && <div style={{fontSize:10,color:"var(--text-muted)",marginTop:1,marginLeft:42}}>{s.description}</div>}
                </div>
              ))}
            </div>}
          </div>
        ))}
      </>}

      <h4 style={{marginTop:12}}>Install from path</h4>
      <div style={{display:"flex",gap:6}}>
        <input value={newSkillPath} onChange={e => setNewSkillPath(e.target.value)} placeholder="/path/to/skill-directory" style={{flex:1}}/>
        <button disabled={saving || !newSkillPath.trim()} onClick={() => act(async () => { await sdk.skills.install(newSkillPath.trim()); setNewSkillPath(""); await refreshSkills() }, `Skill installed`)}>Install</button>
      </div>
    </div>
  );
}
