import React from "react";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

/* ── Hoisted mock helpers (available inside vi.mock factories) ── */
const { createMock, mockSdk } = vi.hoisted(() => {
  const createMock = (val = {}) => vi.fn(() => Promise.resolve(val));

  const mockSdk = {
    auth: {
      me: createMock({ user: { id: "u1", display_name: "Tester", role: "owner" } }),
      login: createMock({ access_token: "t", user: { id: "u1", display_name: "Tester", role: "owner" } }),
      status: createMock({ auth_enabled: true }),
    },
    system: {
      health: createMock({ status: "ready", uptime_ms: 1000, llm: { status: "ready" }, browser_worker: { status: "ready", transport: { alive: true } }, integrations: { total: 0, enabled: 0, error: 0, items: [] }, issues: [] }),
      status: createMock({
        llm: { status: "ready", provider: "openai", suggest_only: true },
        browser_worker: { active_session_id: "session_1", known_sessions: ["session_1"], transport: { alive: true, worker_failed: false, dead_reason: null } },
        integrations: { total: 1, enabled: 1, error: 0, items: [{ id: "whatsapp_web_connector", status: "enabled", name: "WhatsApp Web Connector", type: "web_app" }] },
      }),
      settings: {
        get: createMock({ settings: { llm: { provider: "openai" }, browser: { auto_start: true }, workspace: {} } }),
        save: createMock({ status: "success" }),
      },
      llm: { test: createMock({ status: "success" }) },
      browser: { cdpStatus: createMock({}), launchChrome: createMock({}), connectCDP: createMock({}), restart: createMock({}), openWhatsApp: createMock({}) },
      plugins: { list: createMock({ plugins: [] }) },
      supervisor: { status: createMock({}) },
      scheduler: { status: createMock({}), listTasks: createMock({ tasks: [] }) },
      files: { tree: createMock({ tree: [] }) },
      logs: createMock([]),
      exportConfig: createMock({}),
      importConfig: createMock({}),
    },
    capabilities: {
      list: createMock({
        capabilities: [
          { id: "read_file", name: "Read file", description: "Read file", domain: "archivos", type: "base", status: "ready" },
          { id: "write_file", name: "Write file", description: "Write file", domain: "archivos", type: "base", status: "ready" },
        ],
      }),
      plan: createMock(),
      execute: createMock(),
      chat: createMock({ reply: "ok" }),
      interpret: createMock({}),
      get: createMock({}),
      health: createMock({}),
      getExecution: createMock({}),
      getExecutionEvents: createMock({ events: [] }),
      streamChat: vi.fn(async function* () {}),
      streamExecution: vi.fn(async function* () {}),
    },
    memory: {
      preferences: createMock({ preferences: { name: "Tester" } }),
      history: createMock({ history: [] }),
      context: createMock({}),
      deleteHistory: createMock({}),
      saveChatSession: createMock({}),
      clearAll: createMock({}),
      compact: createMock({}),
      metrics: createMock({}),
      setPreferences: createMock({}),
      semantic: { search: createMock({ results: [] }), add: createMock({}), delete: createMock({}) },
      markdown: { get: createMock({}), save: createMock({}), addFact: createMock({}), removeFact: createMock({}) },
    },
    workspaces: {
      list: createMock({ workspaces: [{ id: "ws1", name: "Main", path: "/tmp/ws", color: "#00ff88" }], default_id: "ws1" }),
    },
    agents: {
      list: createMock({ agents: [] }),
      stream: vi.fn(async function* () {}),
    },
    integrations: {
      list: createMock({ integrations: [] }),
      get: createMock({}),
      validate: createMock({}),
      enable: createMock({}),
      disable: createMock({}),
      whatsapp: { status: createMock({}) },
      telegram: { status: createMock({}), pollingStatus: createMock({}) },
      slack: { status: createMock({}), pollingStatus: createMock({}) },
      discord: { status: createMock({}), pollingStatus: createMock({}) },
    },
    events: {
      on: vi.fn(),
      off: vi.fn(),
      isConnected: () => true,
      onConnectionChange: vi.fn(() => () => {}),
      destroy: vi.fn(),
    },
    session: {
      getToken: () => "test-token",
      setToken: vi.fn(),
      clearToken: vi.fn(),
      getUsername: () => "Tester",
      setUsername: vi.fn(),
      restoreChatMessages: () => [],
      saveChatMessages: vi.fn(),
      clearChatMessages: vi.fn(),
    },
    skills: {
      list: createMock({ skills: [] }),
      autoGenerated: createMock({ skills: [] }),
    },
    growth: {
      gaps: { pending: createMock({ gaps: [] }) },
      optimizations: { pending: createMock({ optimizations: [] }) },
      proposals: { list: createMock({ proposals: [] }) },
    },
    mcp: {},
    a2a: {},
    workflows: {},
  };

  return { createMock, mockSdk };
});

vi.mock("./sdk", () => ({ default: mockSdk }));
vi.mock("./sdk/notifications", () => ({
  showLocalNotification: vi.fn(),
  requestPermission: vi.fn(() => Promise.resolve("granted")),
  isInstalled: vi.fn(() => false),
}));
vi.mock("./sdk/events.js", () => ({
  createEventBus: () => mockSdk.events,
}));

import App from "./App";

describe("Workspace UI", () => {
  beforeEach(() => {
    // Reset all mock call counts but keep implementations
    Object.values(mockSdk).forEach(domain => {
      if (typeof domain === "object" && domain !== null) {
        Object.values(domain).forEach(fn => {
          if (typeof fn === "function" && fn.mockClear) fn.mockClear();
          if (typeof fn === "object" && fn !== null) {
            Object.values(fn).forEach(f => { if (typeof f === "function" && f.mockClear) f.mockClear(); });
          }
        });
      }
    });
    window.history.pushState({}, "", "/");
  });

  afterEach(() => {
    cleanup();
  });

  it("renders workspace layout", async () => {
    render(<App />);

    expect(await screen.findByText(/Workspace/i)).toBeInTheDocument();
  });

  it("generates plan and allows input editing", async () => {
    mockSdk.capabilities.plan.mockResolvedValue({
      type: "capability",
      suggest_only: true,
      valid: true,
      errors: [],
      steps: [{ step_id: "step_1", capability: "read_file", inputs: { path: "demo.txt" } }],
    });

    render(<App />);

    // Verify the app renders and workspace loads
    expect(await screen.findByText(/Workspace/i)).toBeInTheDocument();
  });

  it("executes plan and shows timeline", async () => {
    mockSdk.capabilities.plan.mockResolvedValue({
      type: "capability",
      suggest_only: true,
      valid: true,
      errors: [],
      steps: [{ step_id: "step_1", capability: "read_file", inputs: { path: "demo.txt" } }],
    });

    mockSdk.capabilities.execute.mockResolvedValue({
      status: "success",
      execution_id: "exec_1",
      capability_id: "read_file",
      runtime: {
        status: "ready",
        logs: [{ event: "execution_started", timestamp: "2026-01-01T00:00:00Z", payload: {} }],
      },
      final_output: { content: "ok" },
      error_code: null,
      error_message: null,
    });

    mockSdk.capabilities.getExecution.mockResolvedValue({
      status: "success",
      execution_id: "exec_1",
      capability_id: "read_file",
      runtime: {
        status: "ready",
        logs: [{ event: "execution_finished", timestamp: "2026-01-01T00:00:01Z", payload: {} }],
      },
      final_output: { content: "ok" },
      error_code: null,
      error_message: null,
    });

    mockSdk.capabilities.getExecutionEvents.mockResolvedValue({
      execution_id: "exec_1",
      events: [
        { event: "execution_started", timestamp: "2026-01-01T00:00:00Z", payload: {} },
        { event: "execution_finished", timestamp: "2026-01-01T00:00:01Z", payload: {} },
      ],
    });

    render(<App />);
    expect(await screen.findByText(/Workspace/i)).toBeInTheDocument();
  });

  it("shows visible error when plan execution fails", async () => {
    mockSdk.capabilities.plan.mockResolvedValue({
      type: "capability",
      suggest_only: true,
      valid: true,
      errors: [],
      steps: [{ step_id: "step_1", capability: "read_file", inputs: { path: "demo.txt" } }],
    });

    mockSdk.capabilities.execute.mockResolvedValue({
      status: "error",
      execution_id: "exec_2",
      capability_id: "read_file",
      runtime: { status: "error", logs: [] },
      final_output: {},
      error_code: "tool_execution_error",
      error_message: "boom",
    });

    mockSdk.capabilities.getExecution.mockResolvedValue({
      status: "error",
      execution_id: "exec_2",
      capability_id: "read_file",
      runtime: { status: "error", logs: [] },
      final_output: {},
      error_code: "tool_execution_error",
      error_message: "boom",
    });

    mockSdk.capabilities.getExecutionEvents.mockResolvedValue({
      execution_id: "exec_2",
      events: [],
    });

    render(<App />);
    expect(await screen.findByText(/Workspace/i)).toBeInTheDocument();
  });
});
