"""Core typed contracts for cross-plugin communication.

Plugins never import each other directly — they depend on these Protocol
interfaces.  The ServiceContainer resolves concrete implementations at runtime.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# Event Bus
# ---------------------------------------------------------------------------

@runtime_checkable
class EventBusContract(Protocol):
    def emit(self, event_type: str, data: dict[str, Any] | None = None) -> None: ...
    def subscribe(self, callback: Any) -> Any: ...


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------

@runtime_checkable
class SettingsProvider(Protocol):
    def load_settings(self) -> dict[str, Any]: ...
    def get_settings(self, *, mask_secrets: bool = True) -> dict[str, Any]: ...
    def save_settings(self, payload: dict[str, Any]) -> dict[str, Any]: ...


# ---------------------------------------------------------------------------
# Tool Registry & Runtime
# ---------------------------------------------------------------------------

@runtime_checkable
class ToolRegistryContract(Protocol):
    def get(self, tool_id: str) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def ids(self) -> list[str]: ...
    def register(self, contract: dict[str, Any], *, source: str = "<memory>") -> None: ...


@runtime_checkable
class ToolRuntimeContract(Protocol):
    def execute(self, action: str, params: dict[str, Any]) -> Any: ...
    def register_handler(self, tool_id: str, handler: Any) -> None: ...


# ---------------------------------------------------------------------------
# Capability Registry & Engine
# ---------------------------------------------------------------------------

@runtime_checkable
class CapabilityRegistryContract(Protocol):
    def get(self, capability_id: str) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def ids(self) -> list[str]: ...
    def register(self, contract: dict[str, Any], *, source: str = "<memory>") -> None: ...


@runtime_checkable
class CapabilityEngineContract(Protocol):
    def execute(
        self,
        contract: dict[str, Any],
        inputs: dict[str, Any],
        event_callback: Any = None,
    ) -> dict[str, Any]: ...


# ---------------------------------------------------------------------------
# Interpretation
# ---------------------------------------------------------------------------

@runtime_checkable
class IntentInterpreterContract(Protocol):
    def interpret(self, text: str, history: Any = None) -> dict[str, Any]: ...
    def classify_message(self, text: str) -> str: ...
    def chat_response(self, text: str, user_name: str = "") -> str: ...


@runtime_checkable
class LLMClientContract(Protocol):
    def complete(self, system_prompt: str = "", user_prompt: str = "") -> str: ...


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

@runtime_checkable
class SecurityServiceContract(Protocol):
    def classify(
        self,
        capability_id: str = "",
        tool_id: str = "",
        inputs: dict[str, Any] | None = None,
    ) -> Any: ...

    def classify_description(self, level: Any) -> str: ...


# ---------------------------------------------------------------------------
# Memory
# ---------------------------------------------------------------------------

@runtime_checkable
class MemoryManagerContract(Protocol):
    def recall(self, key: str) -> Any: ...
    def remember(self, key: str, value: Any, **kw: Any) -> Any: ...
    def recall_all(self, memory_type: str | None = None) -> list[dict[str, Any]]: ...
    def forget(self, memory_id: str) -> bool: ...
    def count(self) -> int: ...


@runtime_checkable
class ExecutionHistoryContract(Protocol):
    def upsert_chat(self, session_id: str, intent: str, messages: list | None = None, duration_ms: int = 0, workspace_id: str | None = None) -> str | None: ...
    def get_recent(self, n: int = 20) -> list[dict[str, Any]]: ...
    def get_by_workspace(self, workspace_id: str, limit: int = 50) -> list[dict[str, Any]]: ...
    def get_session(self, execution_id: str) -> dict[str, Any] | None: ...
    def get_stats(self) -> dict[str, Any]: ...
    def count(self) -> int: ...


@runtime_checkable
class SemanticMemoryContract(Protocol):
    def remember_semantic(self, text: str, **kw: Any) -> dict[str, Any] | None: ...
    def recall_semantic(self, query: str, top_k: int = 5) -> list[dict[str, Any]]: ...
    def forget_semantic(self, memory_id: str) -> bool: ...
    def count(self) -> int: ...


@runtime_checkable
class MarkdownMemoryContract(Protocol):
    def load_memory_md(self) -> str: ...
    def save_memory_md(self, content: str) -> None: ...
    def load_memory_sections(self) -> dict[str, list[str]]: ...
    def add_fact(self, section: str, fact: str) -> None: ...
    def remove_fact(self, section: str, fact_substring: str) -> bool: ...
    def append_daily(self, entry: str, section: str = "Sessions") -> None: ...
    def build_context(self, max_tokens: int = 500) -> str: ...


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

@runtime_checkable
class AgentLoopContract(Protocol):
    def run(self, user_message: str, session_id: str | None = None, conversation_history: list | None = None, agent_config: dict[str, Any] | None = None, workspace_id: str | None = None, workspace_path: str | None = None) -> Any: ...
    def get_session(self, session_id: str) -> Any: ...


@runtime_checkable
class AgentRegistryContract(Protocol):
    def list(self) -> list[dict[str, Any]]: ...
    def get(self, agent_id: str) -> dict[str, Any] | None: ...
    def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, agent_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete(self, agent_id: str) -> bool: ...


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------

@runtime_checkable
class WorkspaceRegistryContract(Protocol):
    def list(self) -> list[dict[str, Any]]: ...
    def get(self, ws_id: str) -> dict[str, Any] | None: ...
    def get_default(self) -> dict[str, Any] | None: ...
    def add(self, name: str, path: str, **kw: Any) -> dict[str, Any]: ...
    def remove(self, ws_id: str) -> bool: ...
    def set_default(self, ws_id: str) -> bool: ...
    def update(self, ws_id: str, **kw: Any) -> dict[str, Any] | None: ...


# ---------------------------------------------------------------------------
# Health & Metrics
# ---------------------------------------------------------------------------

@runtime_checkable
class HealthServiceContract(Protocol):
    def get_system_health(self) -> dict[str, Any]: ...


@runtime_checkable
class MetricsCollectorContract(Protocol):
    def get_metrics(self) -> dict[str, Any]: ...
    def record_execution(self, **kw: Any) -> None: ...
