"""Plugin type Protocols — each plugin implements one or more of these."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .context import PluginContext


@runtime_checkable
class BasePlugin(Protocol):
    """Every plugin must implement this base interface."""

    @property
    def plugin_id(self) -> str: ...
    @property
    def plugin_name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def dependencies(self) -> list[str]: ...

    def initialize(self, ctx: PluginContext) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...


@runtime_checkable
class ToolPlugin(BasePlugin, Protocol):
    """Registers tools into the ToolRuntime."""
    def register_tools(self, tool_registry: Any, tool_runtime: Any) -> list[str]: ...


@runtime_checkable
class ChannelPlugin(BasePlugin, Protocol):
    """Registers a messaging channel."""
    @property
    def channel_id(self) -> str: ...
    def get_status(self) -> dict[str, Any]: ...
    def configure(self, settings: dict[str, Any]) -> None: ...
    def send_message(self, target: str, text: str, **kw: Any) -> dict[str, Any]: ...
    def register_routes(self, router: Any) -> None: ...


@runtime_checkable
class MemoryPlugin(BasePlugin, Protocol):
    """Provides a memory backend."""
    def store(self, key: str, value: Any, **kw: Any) -> None: ...
    def retrieve(self, key: str) -> Any: ...
    def search(self, query: str, limit: int = 10) -> list[dict[str, Any]]: ...


@runtime_checkable
class AgentPlugin(BasePlugin, Protocol):
    """Registers agent types or behaviors."""
    def get_agent_types(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class UIPlugin(BasePlugin, Protocol):
    """Registers Control Center UI sections."""
    def get_ui_sections(self) -> list[dict[str, Any]]: ...
    def register_routes(self, router: Any) -> None: ...
