import { get, post, del } from "../client.js";

export const skills = {
  list: () => get("/skills"),
  get: (id) => get(`/skills/${id}`),
  install: (source) => post("/skills/install", { source }),
  uninstall: (id) => del(`/skills/${id}`),
  autoGenerated: () => get("/skills/auto-generated"),
};
