"""
Tests for Componente 4 — CapabilityGenerator.

Validates:
  1. Fallback contract generated when LLM unavailable.
  2. Fallback contract passes schema validation.
  3. LLM-generated contract used when valid JSON returned.
  4. Invalid LLM JSON falls back to template.
  5. Proposal saved to disk and retrievable.
  6. list_proposals returns saved proposal IDs.
  7. delete_proposal removes the file.
  8. Domain normalization for unknown domains.
  9. generate_proposal returns expected shape.
  10. No mutation of registry (proposal only).
"""
from __future__ import annotations

import json
import shutil
import unittest
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

from system.capabilities.registry import CapabilityRegistry
from system.core.interpretation.llm_client import LLMClient, LLMClientError
from system.core.self_improvement.capability_generator import (
    CapabilityGenerator,
    _fallback_contract,
)

ROOT = Path(__file__).resolve().parents[2]
TMP = ROOT / "tests" / "unit" / ".tmp_runtime" / "cap_generator"


def _workspace(name: str) -> Path:
    ws = TMP / name
    if ws.exists():
        shutil.rmtree(ws)
    ws.mkdir(parents=True)
    return ws


def _registry() -> CapabilityRegistry:
    reg = CapabilityRegistry()
    reg.load_from_directory(ROOT / "system" / "capabilities" / "contracts" / "v1")
    return reg


def _failing_llm() -> LLMClient:
    mock = MagicMock(spec=LLMClient)
    mock.complete.side_effect = LLMClientError("LLM unavailable")
    return mock


def _llm_returning(json_text: str) -> LLMClient:
    mock = MagicMock(spec=LLMClient)
    mock.complete.return_value = json_text
    return mock


# ===========================================================================
# 1. Fallback contract
# ===========================================================================

class TestFallbackContract(unittest.TestCase):

    def test_fallback_has_required_fields(self):
        contract = _fallback_contract("send_email", "ejecucion", "Send an email")
        for key in ("id", "name", "domain", "type", "description",
                     "inputs", "outputs", "requirements", "strategy",
                     "exposure", "lifecycle"):
            self.assertIn(key, contract, f"Missing field: {key}")

    def test_fallback_passes_schema_validation(self):
        contract = _fallback_contract("send_email", "ejecucion", "Send an email")
        reg = CapabilityRegistry()
        reg.register(contract, source="test")  # raises if invalid

    def test_fallback_uses_generated_type(self):
        contract = _fallback_contract("my_cap", "archivos", "desc")
        self.assertEqual(contract["type"], "generated")
        self.assertEqual(contract["lifecycle"]["status"], "experimental")

    def test_fallback_normalizes_bad_domain(self):
        contract = _fallback_contract("cap", "invalid_domain", "desc")
        self.assertEqual(contract["domain"], "ejecucion")


# ===========================================================================
# 2. Generator with failing LLM (fallback path)
# ===========================================================================

class TestGeneratorFallbackPath(unittest.TestCase):

    def test_generates_proposal_when_llm_fails(self):
        ws = _workspace("llm_fail")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "send_email",
            "domain": "ejecucion",
            "description": "Send an email via API",
        })
        self.assertEqual(result["capability_id"], "send_email")
        self.assertTrue((ws / "proposals" / "send_email.json").exists())
        self.assertIsInstance(result["contract"], dict)
        self.assertEqual(result["contract"]["id"], "send_email")

    def test_fallback_proposal_is_validated(self):
        ws = _workspace("llm_fail_valid")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "process_csv",
            "domain": "archivos",
            "description": "Process a CSV file",
        })
        self.assertTrue(result["validated"])


# ===========================================================================
# 3. Generator with LLM returning valid JSON
# ===========================================================================

class TestGeneratorLLMSuccess(unittest.TestCase):

    def _valid_llm_contract(self, cap_id: str = "llm_generated_cap") -> str:
        return json.dumps({
            "id": cap_id,
            "name": "LLM Generated",
            "domain": "ejecucion",
            "type": "generated",
            "description": "Generated by LLM",
            "inputs": {"value": {"type": "string", "required": True}},
            "outputs": {"status": {"type": "string"}},
            "requirements": {"tools": ["execution_run_command"], "capabilities": [], "integrations": []},
            "strategy": {
                "mode": "sequential",
                "steps": [{"step_id": "run_it", "action": "execution_run_command",
                           "params": {"command": "echo {{inputs.value}}"}}],
            },
            "exposure": {"visible_to_user": True, "trigger_phrases": ["generate"]},
            "lifecycle": {"version": "1.0.0", "status": "experimental"},
        })

    def test_llm_contract_used_when_valid(self):
        ws = _workspace("llm_ok")
        llm = _llm_returning(self._valid_llm_contract())
        gen = CapabilityGenerator(llm, _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "llm_generated_cap",
            "domain": "ejecucion",
            "description": "Test",
        })
        self.assertEqual(result["contract"]["id"], "llm_generated_cap")
        self.assertEqual(result["contract"]["type"], "generated")
        self.assertTrue(result["validated"])

    def test_invalid_llm_json_falls_back(self):
        ws = _workspace("llm_bad_json")
        llm = _llm_returning("this is not json")
        gen = CapabilityGenerator(llm, _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "test_fallback",
            "domain": "ejecucion",
            "description": "Test",
        })
        # Should use fallback contract
        self.assertEqual(result["contract"]["type"], "generated")
        self.assertEqual(result["contract"]["lifecycle"]["status"], "experimental")

    def test_llm_json_in_markdown_fences(self):
        ws = _workspace("llm_fences")
        raw = "Here is the contract:\n```json\n" + self._valid_llm_contract("fenced_cap") + "\n```"
        llm = _llm_returning(raw)
        gen = CapabilityGenerator(llm, _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "fenced_cap",
            "domain": "ejecucion",
            "description": "Test",
        })
        self.assertEqual(result["contract"]["id"], "fenced_cap")


# ===========================================================================
# 4. Proposal persistence
# ===========================================================================

class TestProposalPersistence(unittest.TestCase):

    def test_save_and_get(self):
        ws = _workspace("persist")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        gen.generate_proposal({"capability_id": "my_cap", "domain": "web", "description": "x"})
        loaded = gen.get_proposal("my_cap")
        self.assertIsNotNone(loaded)
        self.assertEqual(loaded["id"], "my_cap")

    def test_get_nonexistent_returns_none(self):
        ws = _workspace("no_prop")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        self.assertIsNone(gen.get_proposal("ghost"))

    def test_list_proposals(self):
        ws = _workspace("list_props")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        gen.generate_proposal({"capability_id": "cap_alpha", "domain": "ejecucion", "description": "a"})
        gen.generate_proposal({"capability_id": "cap_beta", "domain": "ejecucion", "description": "b"})
        ids = gen.list_proposals()
        self.assertIn("cap_alpha", ids)
        self.assertIn("cap_beta", ids)

    def test_delete_proposal(self):
        ws = _workspace("delete_prop")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        gen.generate_proposal({"capability_id": "del_cap", "domain": "ejecucion", "description": "x"})
        self.assertTrue(gen.delete_proposal("del_cap"))
        self.assertIsNone(gen.get_proposal("del_cap"))
        self.assertFalse(gen.delete_proposal("del_cap"))


# ===========================================================================
# 5. No registry mutation
# ===========================================================================

class TestNoRegistryMutation(unittest.TestCase):

    def test_registry_unchanged_after_generation(self):
        ws = _workspace("no_mutate")
        reg = _registry()
        initial_ids = set(reg.ids())
        gen = CapabilityGenerator(_failing_llm(), reg, ws / "proposals")
        gen.generate_proposal({"capability_id": "new_cap", "domain": "ejecucion", "description": "x"})
        self.assertEqual(set(reg.ids()), initial_ids)


# ===========================================================================
# 6. Gap field extraction
# ===========================================================================

class TestGapFieldExtraction(unittest.TestCase):

    def test_uses_suggested_capability_from_gap(self):
        ws = _workspace("gap_field")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "suggested_capability": "from_gap",
            "intent": "user said something",
        })
        self.assertEqual(result["capability_id"], "from_gap")

    def test_uses_sample_intent_as_description(self):
        ws = _workspace("gap_desc")
        gen = CapabilityGenerator(_failing_llm(), _registry(), ws / "proposals")
        result = gen.generate_proposal({
            "capability_id": "desc_cap",
            "sample_intent": "do something cool",
        })
        self.assertEqual(result["contract"]["description"], "do something cool")


if __name__ == "__main__":
    unittest.main()
